### ISSUE TITLE
Writting down top conformations

### ISSUE THREAD

**Issue by wangsy11** [donaldlab/OSPREY_refactor#16]
Hi,

I couldn't get the top conformations written down as pdb files in a K* design, 'kStarSaveTopConfsAsPDB' was checked to be turned on. It turns out to be observed only when 'kStarPFuncMethod' set to 'parallelConf'. Thanks.

**Comment by cuchaz** [comment]
This is fixed now! Try updating your code to the latest master commit. Let me know if you have any more problems. =)
