### ISSUE TITLE
Synchronization bug with ParallelConfPartitionFunction.compute(int) function

### ISSUE THREAD

**Issue by gokeO** [donaldlab/OSPREY_refactor#23]
Please see multistatekstar.ParallelPartitionFunction.compute(int) in my branch https://github.com/gokeO/OSPREY_refactor for a proposed fix.

To properly exit on Status.NotEnoughConformations or Status.NotEnoughFiniteEnergies, I think you need a wait function that releases the lock. I used java's built wait() and notify() function to achieve the desired functionality. the notify() function is at the end of ecalc.calcEnergyAsync(). this required that i use a variable called numActiveThreads to count down the number of active threads.

**Comment by cuchaz** [comment]
I wasn't sure if this synchronization bug was only of theoretical concern or practical concern, but I recently saw a K* unit test fail because of it, so it's definitely a practical concern now. =P

I'm pushing a commit soon that should fix it for good. Tests are running now. So far, so good.
