### ISSUE TITLE
Questions about epsilon value calculation and conformaiton numbers in output file

### ISSUE THREAD

**Issue by wangsy11** [donaldlab/OSPREY_refactor#26]
Hi,

In some occasions when running new gpu version, I got negative epsilon value in the design process. Besides all conformation numbers wrote down in output file is shown to be 0.

I performed design with non natural amino acids so I forked a branch (no earlier than last week) and committed some slight modifications to fit them: https://github.com/wangsy11/OSPREY_refactor

Thanks a lot.

**Comment by cuchaz** [comment]
Thanks for sharing your code. Now I can run the config files you sent earlier.

I think I know what's causing this. It looks like your config file has
```
DoSolvationE false
```
For the moment, turning off the solvation forcefield energy isn't supported by the GPU code yet. [A newer versions of the code](https://github.com/donaldlab/OSPREY_refactor/commit/6582f85549f86fc582974c74bc3f9d1adca9cabb#diff-d6c1b3dd61f826c97c6d34f189725dc6R39) stops you from doing that, but the code you're using doesn't have that check. Instead, you just get a wrong energy on the GPU, but the correct energy on the CPU.

I'll work on implementing configurable solvation parameters for the GPU code. In the meantime, you can get correct results on the GPU by turning the solvation forcefield back on. Or just use the CPU for your computations.

**Comment by cuchaz** [comment]
This should be fixed in the master branch now. If it's not working for you, feel free to re-open this issue.
