### ISSUE TITLE
Out of Error Memory on gpu-compute7

### ISSUE THREAD

**Issue by eternityslyre** [donaldlab/OSPREY_refactor#67]
I feel like these Nvidia GPU-equipped machines should be able to run OSPREY 3.0a4 just fine. Is this the error we should be seeing?  

  1 jj@gpu-compute7$ python
  2 Python 2.7.12 (default, Nov 19 2016, 06:48:10)
  3 [GCC 5.4.0 20160609] on linux2
  4 Type "help", "copyright", "credits" or "license" for more information.
  5 >>> import osprey
  6 >>> osprey.start()
  7 OSPREY 3.0-alpha4
  8 >>> osprey.printGpuInfo()
  9 Discovering CUDA GPUs... none found
 10 Traceback (most recent call last):
 11     File "<stdin>", line 1, in <module>
 12     File "/usr/project/dlab/Users/jj/OSPREY_Python/python/osprey/__init__.py", line 183, in printGpuInfo
 13         c.gpu.cuda.Diagnostics.main(None)
 14 jpype._jexception.CudaExceptionPyRaisable: jcuda.CudaException: CUDA_ERROR_OUT_OF_MEMORY
 15
 16 jcuda.CudaException: CUDA_ERROR_OUT_OF_MEMORY
 17     at jcuda.driver.JCudaDriver.checkResult(JCudaDriver.java:337)
 18     at jcuda.driver.JCudaDriver.cuCtxCreate(JCudaDriver.java:1514)
 19     at edu.duke.cs.osprey.gpu.cuda.Gpu.<init>(Gpu.java:31)
 20     at edu.duke.cs.osprey.gpu.cuda.Gpus.<init>(Gpus.java:49)
 21     at edu.duke.cs.osprey.gpu.cuda.Gpus.get(Gpus.java:22)
 22     at edu.duke.cs.osprey.gpu.cuda.Diagnostics.main(Diagnostics.java:13)
 23
 24 >>>

**Comment by cuchaz** [comment]
Since those are shared machines, I'm guessing another process is eating up all the GPU memory. You can see what other processes are using the GPUs with the command `nvidia-smi`. Also, note that the sysadmins deemed it appropriate to put the following message on the SSH MOTD:
```
********************************************************************************
***********    Please make sure to use GPU memory conservatively.    ***********
***********    When using tensorflow please use the allow_growth     ***********
***********    option.                                               ***********
********************************************************************************
```
I'm guessing memory starvation is the cause of the crash in this case.

**Comment by eternityslyre** [comment]
You are correct! I tried again this morning and the machine was usable. It was still overloaded and didn't run as fast as the K80s. The department must be working those machines to death. Go us! I'll close this bug.
